export { default as HomePage } from "./HomePage";
export { default as CoursesPage } from "./CoursesPage";
export { default as AboutPage } from "./AboutPage";
export { default as UserContentPage } from "./UserContentPage";
export { default as SignInPage } from "./SignInPage";
export { default as SignUpPage } from "./SignUpPage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as SecuredPageInfo } from "./SecuredPageInfo";
export { default as AdminPage } from "./AdminPage";
